## Pytorch
- 페이스북이 초기 Lua 언어로 개발된 Torch를 파이썬 버전으로 개발하여 2017년도에 공개
- 초기의 Torch는 Numpy 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
- 이후 GPU를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크로 발전시킴
- 파이썬답게 만들어졌고, 유연하면서도 가속화된 계산 속도를 제공

## 파이토치 모듈 구조
- Low level Library : CUDA, C / 하드웨어 접근이 용이하고 빠른 저수준의 언어로 작성이 되어서 병렬처리가 가능한 고속으로 GPU 연산이 가능하도록 구성
- Middle level Engine : C++ / Autograd, ATen, JIT 등의 중간 단계의 엔진
- Top level API : python API로 전체를 아울러서 사용할 수 있게 모듈화 (torch, torch.autograd, torch.nn, torch.multiprocessing, torch.utils 등)

## 파이토치의 구성요소
- torch: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- torch.autograd : 자동 미분 기능을 제공하는 라이브러리
- torch.nn : 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- torch.multiprocessing : 병렬처리 기능을 제공하는 라이브러리
- torch.optim : SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- torch.utils : 데이터 조작 등의 유틸리티 기능 제공
- torch.onnx : ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)
- 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
- 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
- Numpy의 ndarray와 유사
- GPU를 사용한 연산 가속 가능


- 0D Tensor(scalar) / 1D Tensor(vector) / 2D Tensor(matrix) / 3D Tensor, ...

In [1]:
import torch

torch.__version__

'1.7.1'

## 텐서 초기화와 데이터 타입
### 초기화 되지 않은 텐서

In [2]:
x = torch.empty(4, 2)
print(x)

tensor([[2.0283e-19, 6.9772e+22],
        [1.8943e+23, 1.1432e-32],
        [1.3563e-19, 1.8888e+31],
        [8.9066e-15, 1.8888e+31]])


### 무작위로 초기화된 텐서

In [3]:
x = torch.rand(4, 2)
print(x)

tensor([[0.7001, 0.2099],
        [0.5597, 0.4989],
        [0.0897, 0.3313],
        [0.8187, 0.7725]])


### 데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [4]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


### 사용자가 입력한 값으로 텐서 초기화

In [5]:
x = torch.tensor([1, 2, 3, 4])
print(x)

tensor([1, 2, 3, 4])


### 2x4 크기, double 타입, 1로 채워진 텐서

In [6]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


### x와 같은 크기, float 타입, 무작위로 채워진 텐서

In [7]:
x = torch.randn_like(x, dtype=torch.float) #기존의 tensor x와 shape은 같지만 random하게
print(x)

tensor([[ 0.2778, -0.2406, -0.6410,  0.9673],
        [-0.6526, -1.6714,  0.7519, -0.8765]])


### 텐서의 크기 계산

In [8]:
print(x.size())

torch.Size([2, 4])


## 데이터 타입(Data Type)
| Data type | dtype | CPU tensor | GPU tensor |
| ------ | ------ | ------ | ------ |
| 32-bit floating point | `torch.float32` or `torch.float` |`torch.FloatTensor` | `torch.cuda.FloatTensor` |
| 64-bit floating point | `torch.float64` or `torch.double` |`torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point | `torch.float16` or `torch.half` |`torch.HalfTensor` | `torch.cuda.HalfTensor` |
| 8-bit integer(unsinged) | `torch.uint8` |`torch.ByteTensor` | `torch.cuda.ByteTensor` |
| 8-bit integer(singed) | `torch.int8` |`torch.CharTensor` | `torch.cuda.CharTensor` |
| 16-bit integer(signed) | `torch.int16` or `torch.short` |`torch.ShortTensor` | `torch.cuda.ShortTensor` |
| 32-bit integer(signed) | `torch.int32` or `torch.int` |`torch.IntTensor` | `torch.cuda.IntTensor` |
| 64-bit integer(signed) | `torch.int64` or `torch.long` |`torch.LongTensor` | `torch.cuda.LongTensor` |

In [9]:
float_tensor = torch.FloatTensor([1, 2, 3])
print(float_tensor)
print(float_tensor.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
print(float_tensor.short()) # 기존의 float type의 tensor를 short 형태로 type casting 
print(float_tensor.int())
print(float_tensor.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [12]:
int_tensor = torch.IntTensor([1, 2, 3])
print(int_tensor)
print(int_tensor.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [13]:
print(int_tensor.float())
print(int_tensor.double())
print(int_tensor.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


## CUDA Tensors
- .to 메소드를 사용하여 텐서를 어떤 장치로(cpu, gpu)로 옮길 수 있음

In [14]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.6972])
-0.6972368955612183
torch.float32


In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double)) # cpu로 옮기면서 type을 double로 바꾸어라

cuda
tensor([1.], device='cuda:0')
tensor([-0.6972], device='cuda:0')
tensor([0.3028], device='cuda:0')
tensor([0.3028], dtype=torch.float64)


## 다차원 텐서 표현
### 0D Tensor(scalar)
- 하나의 숫자를 담고 있는 텐서
- 축과 형상이 없음

In [16]:
t0 = torch.tensor(0)
print(t0.ndim)  # 차원에 대한 정보
print(t0.shape) # shape에 대한 정보
print(t0)

0
torch.Size([])
tensor(0)


### 1D Tensor(vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [17]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)  # 차원에 대한 정보
print(t1.shape) # shape에 대한 정보
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 2D Tensor(matrix)
- 행렬과 같은 모양으로 두개의 축이 존재
- 일반적인 수치, 통계 데이터 셋이 해당
- 주로 samples과 features를 가진 구조로 사용

In [18]:
t2 = torch.tensor([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])
print(t2.ndim)  # 차원에 대한 정보
print(t2.shape) # shape에 대한 정보
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### 3D Tensor
- 큐브(cube)와 같은 모양으로 세 개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
- 주식 가격 데이터 셋, 시간에 따른 질병 발병 데이터 등이 존재
- 주로 samples, time-steps, features를 가진 구조로 사용

In [19]:
t3 = torch.tensor([[[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]],
                   [[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]],
                   [[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]]])
print(t3.ndim)  # 차원에 대한 정보
print(t3.shape) # shape에 대한 정보
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


### 4D Tensor
- 4개의 축
- 컬러 이미지가 대표적인 사례 (흑백 이미지는 3D Tensor로 가능)
- 주로 samples, height, width, channel을 가진 구조가 사용

### 5D Tensor
- 5개의 축
- 비디오 데이터가 대표적인 사례
- 주로 samples, frames, heights, width, channel을 가진 구조가 사용