### Tensor 생성
- 자주 사용하는 함수가 `rand`, `zeros`, `ones`, 각 함수의 첫 인자는 dimension임

- Dimension 적을 때 tuple로 해도 되고 depackage된 상태로 해도 됨

- `torch.zeros` : returns a tensor filled with the scalar value 0, with the shape defined by the variable argument `size`

- `torch.zeros_like` : returns a tensor filled with the scalar value 0, with the same size as argument `input`

- `torch.ones` : returns a tensor filled with the scalar value 1, with the shape defined by the variable argument `size`

- `torch.arange` : returns a 1D tensor of size (end - start) / step with values from the interval [start, end)

- `torch.linspace` : `np.linspace`랑 동일

- `torch.eye` : returns a 2D tensor with ones on the diagonal and zeros elsewhere

- `torch.empty` : returns a tensor filled with uninitialized data

- `torch.full` : returns a tensor of `size` filled with `fill_value`

- `torch.permute` : returns a view of the original tensor `input` with its dimensions permuted

- `torch.rand` : returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)

- `torch.randint` : returns a tensor filled with random integers generated uniformly between [`low` and `high`)

- `torch.randn` : returns a tensor filled with random numbers from a standard normal distribution

- `torch.randperm` : returns a random permutation of integers from 0 to n - 1

In [15]:
import torch
import numpy as np

x = torch.rand((3, 4))
x

tensor([[0.0451, 0.8324, 0.2319, 0.9732],
        [0.9537, 0.0203, 0.4733, 0.1110],
        [0.1005, 0.9470, 0.2391, 0.9604]])

In [6]:
ex = torch.zeros(2, 4)
ex

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
ex = torch.zeros_like(x)
ex

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ex = torch.arange(0, 10, 1)
ex

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
ex = torch.linspace(0, 10, 10)
ex

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
ex = np.linspace(0, 10, 10)
ex

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [17]:
ex = torch.eye(3)
ex

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
ex = torch.full((2, 2), 10)
ex

tensor([[10, 10],
        [10, 10]])

In [19]:
ex = torch.randperm(5)
ex

tensor([4, 1, 3, 0, 2])

### Tensor 데이터 타입
- `torch.Tensor` vs `torch.tensor` : `.tensor` infers the `dtype` automatically while `.Tensor` returns a `torch.FloatTensor`

- `torch.Tensor` vs `torch.cuda.Tensor` : `.Tensor` occupies CPU memory while `.cuda.Tensor` occupies GPU memory

In [20]:
# size가 2 x 3 인 Float type 텐서 생성

torch.cuda.FloatTensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [21]:
# 특정 list를 Float type tensor로 변환

torch.cuda.FloatTensor([2, 3])

tensor([2., 3.], device='cuda:0')

In [22]:
# dtype 형 변환

x = torch.cuda.FloatTensor([2, 3])
x.type_as(torch.cuda.IntTensor())

tensor([2, 3], device='cuda:0', dtype=torch.int32)

In [25]:
# CPU 텐서로도 형 변환이 자유로운 듯

x = torch.cuda.FloatTensor([2, 3])
x_cpu = x.type_as(torch.IntTensor())
x_cpu

tensor([2, 3], dtype=torch.int32)

### Numpy <-> Tensor

In [28]:
x_np = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1, 2, 3, 4, 5, 6]))
x_np

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x_ts = torch.from_numpy(x_np)
x_ts

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
x_ts[0, 0] = 0
x_ts

tensor([[0, 2, 3],
        [4, 5, 6]])

In [32]:
x_np

array([[0, 2, 3],
       [4, 5, 6]])

- 위에서 보면 알 수 있듯이 tensor로 변환한 뒤에 value를 바꾸면 numpy array도 value가 바뀐다는 것을 볼 수 있음

In [33]:
x_np_ = x_ts.numpy()
x_np_

array([[0, 2, 3],
       [4, 5, 6]])

In [34]:
x_np_[0, 0] = 1
x_np_

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
x_ts

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
x_np

array([[1, 2, 3],
       [4, 5, 6]])

- 위에서 보면 알 수 있다시피 numpy array로 부터 바뀐 tensor를 `.numpy()`를 통해 변환을 해주고 값을 바꿔도 모든 value들이 바뀐다는 것을 알 수 있음

### CPU tensor <-> GPU tensor