## 텐서의 연산(operations)
- 텐서에 대한 수학 연산, 삼각함수, 비트 연산, 비교 연산 ,집계 등을 제공

In [6]:
import math
import torch

a = torch.rand(1, 2) * 2 -1
print(a)
print(torch.abs(a))   # 절댓값
print(torch.ceil(a))  # 올림
print(torch.floor(a)) # 내림
print(torch.clamp(a, -0.5, 0.5)) # min = 0.5, max = 0.5로 값을 한정시켜줌

tensor([[ 0.5690, -0.8463]])
tensor([[0.5690, 0.8463]])
tensor([[1., -0.]])
tensor([[ 0., -1.]])
tensor([[ 0.5000, -0.5000]])


In [7]:
print(a)
print(torch.min(a))  # 최솟값
print(torch.max(a))  # 최댓값
print(torch.mean(a)) # 평균값
print(torch.std(a))  # 표준편차
print(torch.prod(a)) # 모든 원소의 곱
print(torch.unique(torch.tensor([1, 2, 3, 1, 1, 2])))  # 유니크한 값을 추출

tensor([[ 0.5690, -0.8463]])
tensor(-0.8463)
tensor(0.5690)
tensor(-0.1387)
tensor(1.0008)
tensor(-0.4816)
tensor([1, 2, 3])


### `max`와 `min`은 `dim` 인자를 줄 경우 argmax와 argmin도 함께 리턴
- argmax: 최대값을 가진 인덱스
- argmin: 최소값을 가진 인덱스

In [8]:
x = torch.rand(2, 2)
print(x)
print(x.max(dim=0)) # [5919, 9191] 과 [7229, 4560] 중에 최댓값과 indicies
print(x.max(dim=1)) # [5919, 7229] 과 [9191, 4560] 중에 최댓값과 indicies

tensor([[0.5919, 0.7229],
        [0.9191, 0.4560]])
torch.return_types.max(
values=tensor([0.9191, 0.7229]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.7229, 0.9191]),
indices=tensor([1, 0]))


In [9]:
print(x)
print(x.min(dim=0)) # [5919, 9191] 과 [7229, 4560] 중에 최솟값과 indicies
print(x.min(dim=1)) # [5919, 7229] 과 [9191, 4560] 중에 최솟값과 indicies

tensor([[0.5919, 0.7229],
        [0.9191, 0.4560]])
torch.return_types.min(
values=tensor([0.5919, 0.4560]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.5919, 0.4560]),
indices=tensor([0, 1]))


In [10]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.2243, 0.5606],
        [0.0220, 0.9639]])
tensor([[0.3646, 0.2245],
        [0.3986, 0.8700]])


`torch.add` :덧셈

In [11]:
print(x + y)
print(torch.add(x, y))

tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])
tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])


### 결과 텐서를 인자로 제공

In [12]:
result = torch.empty(2, 2)
torch.add(x, y, out=result)
print(result)

tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])


`in-place` 방식
- in-place 방식으로 텐서의 값을 변경하는 연산 뒤에는 _가 붙음
- `x.copy_(y)`, `x.t_()`

In [13]:
print(x)
print(y)
y.add_(x) # (y값에 x를 더한 값)을 y에 할당
print(y)

tensor([[0.2243, 0.5606],
        [0.0220, 0.9639]])
tensor([[0.3646, 0.2245],
        [0.3986, 0.8700]])
tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])


`torch.sub` : 뺄셈

In [14]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[0.2243, 0.5606],
        [0.0220, 0.9639]])
tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])
tensor([[-0.3646, -0.2245],
        [-0.3986, -0.8700]])
tensor([[-0.3646, -0.2245],
        [-0.3986, -0.8700]])
tensor([[-0.3646, -0.2245],
        [-0.3986, -0.8700]])


`torch.mul` : 곱셈

In [15]:
print(x)
print(y)
print(x * y)
print(torch.mul(x, y)) # broadcasting to a common shape
print(x.mul(y))

tensor([[0.2243, 0.5606],
        [0.0220, 0.9639]])
tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])
tensor([[0.1321, 0.4402],
        [0.0093, 1.7676]])
tensor([[0.1321, 0.4402],
        [0.0093, 1.7676]])
tensor([[0.1321, 0.4402],
        [0.0093, 1.7676]])


`torch.div` : 나눗셈

In [16]:
print(x)
print(y)
print(x / y)
print(torch.div(x, y)) # broadcasting to a common shape
print(x.div(y))

tensor([[0.2243, 0.5606],
        [0.0220, 0.9639]])
tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])
tensor([[0.3809, 0.7140],
        [0.0523, 0.5256]])
tensor([[0.3809, 0.7140],
        [0.0523, 0.5256]])
tensor([[0.3809, 0.7140],
        [0.0523, 0.5256]])


`torch.mm` : 내적(dot product)

In [17]:
print(x)
print(y)
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z)
print(torch.svd(z)) # 행렬 분해

tensor([[0.2243, 0.5606],
        [0.0220, 0.9639]])
tensor([[0.5889, 0.7852],
        [0.4206, 1.8339]])
tensor([[0.3679, 1.2042],
        [0.4183, 1.7849]])
tensor([[0.3679, 1.2042],
        [0.4183, 1.7849]])
torch.return_types.svd(
U=tensor([[-0.5659, -0.8245],
        [-0.8245,  0.5659]]),
S=tensor([2.2230, 0.0688]),
V=tensor([[-0.2488, -0.9686],
        [-0.9686,  0.2488]]))


## 텐서의 조작(Manipulations)
### 인덱싱(Indexing) : Numpy 처럼 인덱싱 형태로 사용 가능

In [19]:
x = torch.Tensor([[1, 2],
                  [3, 4]])
print(x)

# Indexing
print(x[0, 0])
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])

# Slicing
print(x[:, 0])
print(x[:, 1])
print(x[0, :])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


`view` : 텐서의 크기 (size)나 모양 (shape) 을 변경
- 기본적으로 변경 전과 후에 텐서 안의 원소 개수가 유지되어야 함
- -1로 설정하면 계산을 통해 해당 크기 값을 유추

In [20]:
x = torch.randn(4, 5) # torch.rand -> uniform distribution [0, 1] / torch.randn -> normal distribution N(0, 1)
print(x)

y = x.view(20)
print(y)

z = x.view(5, -1)
print(z)

tensor([[-1.6201, -0.0748,  0.0319,  1.0749,  0.5060],
        [ 0.8977, -0.8161,  1.9575,  0.0190, -1.7782],
        [ 0.2932, -1.5644,  0.8408, -0.5536, -0.0986],
        [-0.0557, -0.1520, -1.2452,  0.4618,  0.1852]])
tensor([-1.6201, -0.0748,  0.0319,  1.0749,  0.5060,  0.8977, -0.8161,  1.9575,
         0.0190, -1.7782,  0.2932, -1.5644,  0.8408, -0.5536, -0.0986, -0.0557,
        -0.1520, -1.2452,  0.4618,  0.1852])
tensor([[-1.6201, -0.0748,  0.0319,  1.0749],
        [ 0.5060,  0.8977, -0.8161,  1.9575],
        [ 0.0190, -1.7782,  0.2932, -1.5644],
        [ 0.8408, -0.5536, -0.0986, -0.0557],
        [-0.1520, -1.2452,  0.4618,  0.1852]])


`item` : 텐서에 값이 단 하나라도 존재하면 숫자 값을 얻을 수 있음

In [21]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.6699])
0.6699197292327881
torch.float32


스칼라값이 하나만 존재해야 `item()` 사용 가능

In [22]:
x = torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.1240, -1.1057])


ValueError: only one element tensors can be converted to Python scalars

`squeeze` : 차원을 축소 (제거)

In [23]:
tensor = torch.rand(1, 3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.2018, 0.1002, 0.8639],
         [0.6126, 0.8541, 0.8025],
         [0.0386, 0.2268, 0.1836]]])
torch.Size([1, 3, 3])


In [24]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.2018, 0.1002, 0.8639],
        [0.6126, 0.8541, 0.8025],
        [0.0386, 0.2268, 0.1836]])
torch.Size([3, 3])


`unsqueeze` : 차원을 증가 (생성)

In [25]:
t = torch.randn(3, 3)
print(t)
print(t.shape)

tensor([[-0.8666, -1.5095, -1.3543],
        [-0.8686,  0.4340,  1.4451],
        [ 0.4265, -0.5472,  0.4400]])
torch.Size([3, 3])


In [26]:
tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[-0.8666, -1.5095, -1.3543],
         [-0.8686,  0.4340,  1.4451],
         [ 0.4265, -0.5472,  0.4400]]])
torch.Size([1, 3, 3])


In [27]:
tensor = t.unsqueeze(dim=1)
print(tensor)
print(tensor.shape)

tensor([[[-0.8666, -1.5095, -1.3543]],

        [[-0.8686,  0.4340,  1.4451]],

        [[ 0.4265, -0.5472,  0.4400]]])
torch.Size([3, 1, 3])


In [28]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[-0.8666],
         [-1.5095],
         [-1.3543]],

        [[-0.8686],
         [ 0.4340],
         [ 1.4451]],

        [[ 0.4265],
         [-0.5472],
         [ 0.4400]]])
torch.Size([3, 3, 1])


`stack` : 텐서 간 결합

In [31]:
x = torch.FloatTensor([1, 4])
print(x)
print(x.shape)
y = torch.FloatTensor([2, 5])
print(y)
z = torch.FloatTensor([3, 6])
print(z)

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z]).shape)


tensor([1., 4.])
torch.Size([2])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


`cat` : 텐서를 결합하는 메소드(concatenate)
- Numpy의 `stack`과 유사하지만, 쌓을 `dim`이 존재해야함
- 해당 차원을 늘려준 후 결합

In [32]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1, 3, 3)
print(b)

c = torch.cat((a, b), dim=0) # 첫번째 차원을 기준으로 합친다 (1, 3, 3) + (1, 3, 3) -> (2, 3, 3)
print(c)
print(c.size())

tensor([[[ 1.0809,  1.3529,  0.0668],
         [ 0.0224,  2.8311,  0.3062],
         [-0.7540,  1.2852,  1.6618]]])
tensor([[[ 0.6930,  0.0942, -0.6376],
         [-0.2594, -0.0231,  0.0584],
         [ 1.9755, -1.0531,  0.2450]]])
tensor([[[ 1.0809,  1.3529,  0.0668],
         [ 0.0224,  2.8311,  0.3062],
         [-0.7540,  1.2852,  1.6618]],

        [[ 0.6930,  0.0942, -0.6376],
         [-0.2594, -0.0231,  0.0584],
         [ 1.9755, -1.0531,  0.2450]]])
torch.Size([2, 3, 3])


In [33]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1, 3, 3)
print(b)

c = torch.cat((a, b), dim=1) # 두번째 차원을 기준으로 합친다 (1, 3, 3) + (1, 3, 3) -> (2, 3, 3)
print(c)
print(c.size())

tensor([[[-0.8245, -0.3230, -0.4400],
         [-0.0952, -0.6574, -0.4227],
         [-0.9270,  0.1646, -0.1697]]])
tensor([[[-0.2547, -0.3720,  0.8828],
         [-1.5612, -0.2270, -0.3232],
         [ 0.4692, -0.6948, -0.4745]]])
tensor([[[-0.8245, -0.3230, -0.4400],
         [-0.0952, -0.6574, -0.4227],
         [-0.9270,  0.1646, -0.1697],
         [-0.2547, -0.3720,  0.8828],
         [-1.5612, -0.2270, -0.3232],
         [ 0.4692, -0.6948, -0.4745]]])
torch.Size([1, 6, 3])


In [34]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1, 3, 3)
print(b)

c = torch.cat((a, b), dim=2) # 세번째 차원을 기준으로 합친다 (1, 3, 3) + (1, 3, 3) -> (2, 3, 3)
print(c)
print(c.size())

tensor([[[ 2.3680,  0.6793, -1.1438],
         [-0.3439, -1.9585, -1.7374],
         [ 0.2403, -0.0509,  1.2855]]])
tensor([[[ 0.8212, -0.3561,  0.6928],
         [ 1.2615, -2.8948,  0.3840],
         [ 0.4064, -0.3171, -2.0440]]])
tensor([[[ 2.3680,  0.6793, -1.1438,  0.8212, -0.3561,  0.6928],
         [-0.3439, -1.9585, -1.7374,  1.2615, -2.8948,  0.3840],
         [ 0.2403, -0.0509,  1.2855,  0.4064, -0.3171, -2.0440]]])
torch.Size([1, 3, 6])


`chunk` : 텐서를 여러 개로 나눌 때 사용 (몇 개로 나눌 것인가?)

In [35]:
tensor = torch.rand(3, 6)
print(tensor)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1) # dimension 1에서 3개로 나눈다.
print(t1)
print(t2)
print(t3)

tensor([[0.8227, 0.3187, 0.0762, 0.4225, 0.6764, 0.0352],
        [0.3817, 0.6011, 0.5040, 0.6368, 0.4655, 0.3252],
        [0.7483, 0.6877, 0.5664, 0.0390, 0.6448, 0.2865]])
tensor([[0.8227, 0.3187],
        [0.3817, 0.6011],
        [0.7483, 0.6877]])
tensor([[0.0762, 0.4225],
        [0.5040, 0.6368],
        [0.5664, 0.0390]])
tensor([[0.6764, 0.0352],
        [0.4655, 0.3252],
        [0.6448, 0.2865]])


`split` : `chunk`와 동일한 기능이지만 조금 다름 (텐서의 크기는 몇인가?)

In [36]:
tensor = torch.randn(3, 6)
print(tensor)
t1, t2 = torch.split(tensor, 3, dim=1) # dimension 1에서 tensor 크기 3으로 나눈다
print(t1)
print(t2)

tensor([[-0.2974, -0.5813, -0.2371, -0.4320, -1.1664,  0.0810],
        [ 0.5840, -1.5104, -0.4699,  0.8266,  0.1170, -0.3296],
        [-1.0123, -0.5910,  0.2007, -0.0392, -1.3660,  1.8567]])
tensor([[-0.2974, -0.5813, -0.2371],
        [ 0.5840, -1.5104, -0.4699],
        [-1.0123, -0.5910,  0.2007]])
tensor([[-0.4320, -1.1664,  0.0810],
        [ 0.8266,  0.1170, -0.3296],
        [-0.0392, -1.3660,  1.8567]])


### torch &harr; numpy
- Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능
    - `numpy()`
    - `from_numpy()`
- Tensor가 CPU 상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면 다른 하나도 변함


In [37]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [38]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [39]:
a.add_(1)
print(a) # a의 값은 torch로 선언된 값. 하지만 numpy로 바꾼 b도 a와 같이 메모리를 공유하므로 동시에 같이 바뀜
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [41]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a) # a에 1을 더하고 그 값을 a에 할당시켜줌
print(a)    # cpu에 있을 때 마찬가지로 numpy와 tensor는 변환되어도 같은 메모리를 공유한다.
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
